package duke.dukeutility.enums;

/**
 * @see duke.command.Command
 */
public enum ResponseType {
    ECHO,
    EXIT_LOOP,
    ERROR_COMMAND_EXECUTION,
    ERROR_REQUEST_INVALID_PARAMETERS,
    ERROR_REQUEST_INVALID_SYNTAX,
    ERROR_REQUEST_UNKNOWN,
    ERROR_INVALID_READ_FILE_PATH,
    EXPORT_IN_PROGRESS,
    FILE_SAVED,
    FILE_READ,
    ERROR_SAVE_FAILURE,
    TASK_CREATING_IN_PROGRESS,
    TASK_CREATE_TODO,
    TASK_CREATE_DEADLINE,
    TASK_CREATE_EVENT,
    TASK_DELETE_TASK,
    TASK_LIST_ALL,
    TASK_LIST_FIND,
    TASK_STATS_ALL,
    TASK_PROJECTION,
    TASK_IMPORT_TODO,
    TASK_IMPORT_EVENT,
    TASK_IMPORT_DEADLINE,
    TASK_UPDATE_COMPLETE,
    TASK_UPDATE_INCOMPLETE,
    TASK_NOT_FOUND,
}
